---
layout: post
title: "Insights from the Evangelisitc Identity of the Early Church, Part 2"
author: Titus Barnes
date: "2024-07-18"
categories:
image:
featured: true
---

Have you ever stopped to think about how bizarre the behavior of the early church was? Or have you ever wondered at the wildfire-like spread of Christianity that we read about in the New Testament? The book of Acts recounts for us the rapid growth of the church after Jesus commissioned his disciples before ascending into heaven. The church was living boldly, and thousands of people were hearing the gospel, repenting of their sins, and believing in Christ. So what happened to make the early church so evangelistic? And what kind of attitude did this event instill in early believers? This seems like a good place to begin our examination of the evangelistic identity of the early church. Our goal is to, as best we can, make sense of the extraordinary—dare I say supernatural—boldness that we see in the early church's proclamation of the gospel. After all, Christians were dying for this message. And when we can hardly bring ourselves to share the gospel in a place where we flaunt freedom of speech and freedom of religion (speaking for Americans), we ought to ask ourselves, what is going on with these Christians in the early church? What drove them to share the gospel so unabashedly?

### "The Event"
Evangelism is a practice that is motivated by a supposed reality — namely, that God became a man, that he walked among us, that he died a horrific death to pay for the sins of humanity, and that he came back to life three days after having been crucified. This supposed reality of the Incarnation, the historical appearance of God on earth in the form of a man, is what Bruce Shelley calls in his book, [_Church History in Plain Language_](https://www.amazon.com/dp/0310115965?tag=bravesoftwa04-20&linkCode=osi&th=1&psc=1&language=en_US), "the Event." To understand how the Event drove the early church, we must first answer Jesus' question to His disciples in Matthew 16, "Who do you say that I am?" Before we consider how the early church would answer this, let's take a look at how a Greek philosopher writing 150 years after Jesus' life would respond to the question. The following is an excerpt from Origen's apologetic response to a man named Celsus (fl. 2nd century AD), who had a particular distaste for Jesus and his followers. Origen writes:

> After this [Celsus] represents the Jew as having a conversation with Jesus himself and refuting him on many charges, as he thinks: first, because 'he fabricated the story of his birth from a virgin'; and he reproaches him because 'he came from a Jewish village and from a poor country woman who earned her living by spinning.' He says that 'she was driven out by her husband, who was a carpenter by trade, as she was convicted of adultery.' Then he says that 'after she had been driven out by her husband and while she was wandering about in a disgraceful way she secretly gave birth to Jesus.' And he says that 'because he was poor he hired himself out as a workman in Egypt, and there tried his hand at certain magical powers on which Egyptians pride themselves; he returned full of conceit because of these powers, and on account of them gave himself the title of God.' (Turabian citation here)

So Celsus' answer to the question was that Jesus of Nazareth was a lying lunatic who deceived others for his own benefit. The early church, of course, would answer Jesus' question very differently. For years, the prophets had spoken of God's promised Messiah, who would deliver his people. From what he would deliver them was apparently a mystery to the people. In their darkened understanding, many saw themselves as in need of political liberation, but certainly not spiritual liberation. All of a sudden, this man named Jesus from a podunk town in Galilee comes on the scene. When Jesus came, he demonstrated what the Scriptures had been saying all this time — the Messiah would come to save his people from their own wickedness. During his ministry, Jesus made some bold claims, which many deemed blasphemous. In fact, his statements about himself sent the religious leaders into a murderous rage. Why? What was this man saying? You've likely heard this a thousand times, but don't miss this — _Jesus said he was God_. He claimed that he was the Messiah who was to come and deliver his people from their sins and that no one could come to the Father except through _him_.

In response to this claim, some rejected him and even tried to kill him, while others believed him and followed him, eager to hear more of his profound teachings. This Jesus of Nazareth caused quite the stir throughout the surrounding areas. And then all took an unexpected and tragic turn. Jesus was handed over to the Jewish authorities by one of his disciples, Judas called Iscariot. You know the rest of the story. Jesus was tried before Pilate and eventually crucified for his "blasphemous" claims and teachings. To his disciples, all seemed lost. But what happened next changed everything. Jesus came back to life. The Event had been confirmed. God really did walk among us. The Messiah has finally come. To those who believed in Jesus as the Messiah, he was not a lying lunatic who spat blasphemy, he was exactly who he said he was - he was God with us.

### Conviction and Enthusiasm
This fundamental conviction is what drove many early Christians to die with the gospel message on their lips. They believed that Jesus was their God in the flesh and that he really did die for their sins. And they were convinced that he had come back to life three days later, that even death itself could not keep him down. This unlikely reality, that God would come down to earth and die for wicked people, is what distinguishes Christianity and Christians themselves from any other religious belief system. Bruce Shelley captures this idea beautifully when he writes, "Christianity is the only major religion to have as its central event the humiliation of its God" (Shelley, 7). If we are going to understand why the early Christians shared the gospel as boldly as they did, we need to understand that they were _radically compelled_ by the reality of the Event. Michael Green comments on this idea: "The resurrection came to them as God's vindication of the claims Jesus had made. They saw that he was 'designated Son of God in power by his resurrection from the dead.' And they proceeded to announce these joyful tidings with tireless zeal and boundless enthusiasm" (Green, 78).

Green makes a helpful point here. First, he directly ties the reality of the resurrection to the evangelistic zeal of the early church. He understands that there is an inseparable correlation between their behavior and their belief. Second, Green uses a word to describe this behavior of the early church — _enthusiaism_. Both Green and Shelley agree that enthusiasm was a defining characteristic of the early church. They did not share the gospel out of a sense of dreaded obligation or guilt. Instead, their evangelism was driven by _conviction_ and _enthusiasm_. They were not just convinced of the truth of this message, they were excited about it! They knew that others needed this message too, and they would go next door, to the ends of the earth, and to the grave in order to tell others about this good news. 

